# .github/workflows/release.yml
# 最终的、完全校准的工作流

name: Build and Release Geosite

on:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run even if already up-to-date?'
        type: boolean
        required: true
        default: false
  schedule:
    - cron: "0 0 * * *"

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
      
      - name: Build geosite and Generate Outputs
        id: build
        env:
          NO_SKIP: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.force_run == 'true' }}
        run: go run .

      # 将当前仓库地址 (例如 "Jimmyzxk/sing-geosite") 传给脚本
      - name: Commit and Push Rule Set Updates
        if: steps.build.outputs.skip != 'true'
        run: .github/release-rule-set.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }} 

      - name: Generate SHA256 Hashes
        if: steps.build.outputs.skip != 'true'
        run: |
          sha256sum geosite.db > geosite.db.sha256sum
          sha256sum geosite-cn.db > geosite-cn.db.sha256sum

      # 将当前仓库地址传给脚本
      - name: Commit and Push Branch Updates
        if: steps.build.outputs.skip != 'true'
        run: .github/release-branch.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: Delete Older Releases using GitHub CLI
        if: steps.build.outputs.skip != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }} 
        run: |
          gh release list --limit 100 --json tagName --jq '.[].tagName' | \
            tail -n +11 | \
            xargs -I {} gh release delete {} --cleanup-tag --yes

      - name: Create New GitHub Release
        if: steps.build.outputs.skip != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.build.outputs.tag }}
          files: |
            geosite.db
            geosite.db.sha256sum
            geosite-cn.db
            geosite-cn.db.sha256sum
