# .github/workflows/release.yml
# 最终的、简洁的工作流（已修正 Action 版本号）

name: Build and Release Geosite

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # 需要权限来创建Release和推送更新

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # 使用最新的 v4

      - name: Setup Go Environment
        uses: actions/setup-go@v5 # 使用最新的 v5
        with:
          go-version: '^1.22'
      
      # 步骤 1: 运行智能的Go程序
      - name: Build geosite and Generate Outputs
        id: build
        run: go run .

      # 步骤 2: 根据Go程序的决策结果，执行后续操作
      - name: Commit and Push Rule Set Updates
        if: steps.build.outputs.skip != 'true'
        run: .github/release-rule-set.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate SHA256 Hashes
        if: steps.build.outputs.skip != 'true'
        run: |
          sha256sum geosite.db > geosite.db.sha256sum
          sha256sum geosite-cn.db > geosite-cn.db.sha256sum

      - name: Commit and Push Branch Updates
        if: steps.build.outputs.skip != 'true'
        run: .github/release-branch.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- 这里是修正过的版本号 ---
      - name: Delete Older Releases
        if: steps.build.outputs.skip != 'true'
        uses: dev-drprasad/delete-older-releases@v1.0.0 # <-- 从 v1.1.0 修正为正确的 v1.0.0
        with:
          keep_latest: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 步骤 3: 创建新的 GitHub Release
      - name: Create New GitHub Release
        if: steps.build.outputs.skip != 'true'
        uses: softprops/action-gh-release@v2 # 使用最新的 v2
        with:
          tag_name: ${{ steps.build.outputs.tag }}
          files: |
            geosite.db
            geosite.db.sha256sum
            geosite-cn.db
            geosite-cn.db.sha256sum
